#ifndef KITNETWORK_GLOBAL_H
#define KITNETWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KITNETWORK_LIBRARY)
#  define KITNETWORK_EXPORT Q_DECL_EXPORT
#else
#  define KITNETWORK_EXPORT Q_DECL_IMPORT
#endif

#endif // KITNETWORK_GLOBAL_H
